language: java
before_install:
  - unset GEM_PATH
before_script: 
  - mvn -e -Popenlayers
script: mvn -e -Pjenkins verify
after_success:
  - mvn -e -Djavax.xml.accessExternalSchema=file -Pjenkins cobertura:cobertura coveralls:cobertura
jdk:
  - openjdk7
  - oraclejdk8
cache:
  directories:
  - cache
